name: Java Maven CI Pipeline

on:
  push:
    branches: [ "test_branch" ]
  pull_request:
    branches: [ "test_branch" ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and run tests
        run: mvn -B  clean verify
      - name: Start application
        run: |
            echo "Starting Spring Boot application..."
            nohup java -jar target/demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            APP_PID=$!
            echo "App PID: $APP_PID"
            echo $APP_PID > app.pid

      - name: Wait for application & health-check with timeout
        run: |
            echo "Waiting for application to become healthy (timeout 30s)..."
            for i in {1..50}; do
            STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080/health || true)
            if [ "$STATUS" = "200" ]; then
                echo " Application is healthy!"
                exit 0
            fi
                echo "Health not ready yet... retry ($i/50)"
            sleep 1
            done
            echo " Timeout reached — application is not healthy!"
            exit 1

      - name: Stop application
        if: always()
        run: |
            if [ -f app.pid ]; then
            PID=$(cat app.pid)
            echo "Stopping application with PID $PID"
            kill $PID || true
            fi

      #- name: Generate SpotBugs report
       # run: mvn spotbugs:spotbugs

      - name: Archive raw build outputs
        uses: actions/upload-artifact@v4
        with:
          name: raw-target-folder
          path: target/
          retention-days: 7

  reports:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: raw-target-folder
          path: target/

      # - name: Upload SpotBugs Report (HTML/XML)
        # uses: actions/upload-artifact@v4
        # with:
          # name: spotbugs-report
          # path: |
            # target/spotbugs.html
            # target/spotbugsXml.xml

      # - name: Upload JaCoCo Coverage Report
        # uses: actions/upload-artifact@v4
        # with:
          # name: jacoco-report
          # path: target/site/jacoco/
